In [1]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

## Exercise 1

In [2]:
D = np.array([
    [5,6,7],
    [3,4,2],
    [8,7,6]
])
O = np.array([
    [4],
    [5],
    [6]
])
print(D)
print(D.shape)
print(O)
print(O.shape)

[[5 6 7]
 [3 4 2]
 [8 7 6]]
(3, 3)
[[4]
 [5]
 [6]]
(3, 1)


In [3]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.25641026, -0.33333333,  0.41025641],
       [ 0.05128205,  0.66666667, -0.28205128],
       [ 0.28205128, -0.33333333, -0.05128205]])

In [4]:
r = D_inv @ O 
r

array([[-0.23076923],
       [ 1.84615385],
       [-0.84615385]])

In [5]:
D @ r

array([[4.],
       [5.],
       [6.]])

In [6]:
A = np.array([
    [6,7,6],
    [7,6,5],
    [5,5,5]
])
R = np.array([
    [3],
    [6],
    [8]
])
print(A)
print(A.shape)
print(R)
print(R.shape)

[[6 7 6]
 [7 6 5]
 [5 5 5]]
(3, 3)
[[3]
 [6]
 [8]]
(3, 1)


In [7]:
A_inv = np.linalg.inv(A)
A_inv

array([[-5.0000000e-01,  5.0000000e-01,  1.0000000e-01],
       [ 1.0000000e+00, -1.1956248e-16, -1.2000000e+00],
       [-5.0000000e-01, -5.0000000e-01,  1.3000000e+00]])

In [8]:
r = A_inv @ R 
r

array([[ 2.3],
       [-6.6],
       [ 5.9]])

In [9]:
A @ r

array([[3.],
       [6.],
       [8.]])

TypeError: _solve_dispatcher() missing 1 required positional argument: 'b'